### ISSUE TITLE
Documentation is missing.

### ISSUE THREAD

**Issue by poljar** [ruma/ruma-events-macros#2]
The events macros seem to be missing documentation.

The [documentation page](https://docs.rs/crate/ruma-events-macros/0.2.0) states this:
> ruma-events-macros has comprehensive documentation available on docs.rs.

Yet on the same page we find this:
> ruma-events-macros-0.2.0 doesn't have any documentation.

**Comment by jplatte** [comment]
This seems to be a docs.rs bug: https://github.com/rust-lang/docs.rs/issues/422

**Comment by pietroalbini** [comment]
Hello! Pietro from the docs.rs team here. Sorry for the issue, we fixed the underlying bug and rebuilt your crate's documentation: https://docs.rs/ruma-events-macros/0.2.0/ruma_events_macros/
